FROM golang:1.25-alpine3.22 AS builder

COPY . /app
WORKDIR /app

RUN CGO_ENABLED=0 go build -mod vendor -o /bin/main ./cmd/audit/

FROM alpine:3.22 AS runner

COPY --from=builder /bin/main /bin/main
ENTRYPOINT ["/bin/main"]
